version: '2'
services:
  php:
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www/
      - $HOME/.composer/:$HOME/.composer/
    environment:
      - "DB_HOST=mysql"
      - "DB_DATABASE=homestead"
      - "DB_USERNAME=homestead"
      - "DB_PASSWORD=homestead"
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"
    # extra_hosts:
    #   - "one.fake:nginx"
    #   - "two.fake:nginx"
  nginx:
    build:
      context: ./docker/nginx
    volumes_from:
      - php
    volumes:
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    networks:
      default:
        aliases:
          - one.fake
          - two.fake
  mysql:
    image: mysql:5.7
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=homestead"
    ports:
      - "3307:3306"

  redis:
    image: redis:4.0-alpine
    command: redis-server --appendonly yes


volumes:
  mysqldata:
  pgsqldata: